// Code generated by protoc-gen-go.
// source: proxy.proto
// DO NOT EDIT!

/*
Package proxymsg is a generated protocol buffer package.

It is generated from these files:
	proxy.proto

It has these top-level messages:
	InternalMessage
	Proxy_GS_MS_Match
	Proxy_GS_MS_MakeTeamOperate
	Proxy_GS_MS_Offline
	Proxy_GS_BS_Query_BattleInfo
	Proxy_GS_MS_Reconnect
	Proxy_MS_BS_AllocBattleRoom
	Proxy_MS_GS_Begin_Battle
	Proxy_MS_GS_Reconnect
	Proxy_BS_MS_AllocBattleRoom
	Proxy_BS_GS_Query_BattleInfo
	Proxy_BS_GS_FINISH_BATTLE
	Proxy_BS_MS_SyncBSInfo
*/
package proxymsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ProxyMessageType int32

const (
	ProxyMessageType_PMT_GS_MS_MATCH             ProxyMessageType = 0
	ProxyMessageType_PMT_MS_BS_ALLOCBATTLEROOM   ProxyMessageType = 1
	ProxyMessageType_PMT_MS_GS_MATCH_RESULT      ProxyMessageType = 2
	ProxyMessageType_PMT_BS_MS_ALLOCBATTLEROOM   ProxyMessageType = 3
	ProxyMessageType_PMT_MS_GS_BEGIN_BATTLE      ProxyMessageType = 4
	ProxyMessageType_PMT_GS_MS_CHOOSE_OPERATE    ProxyMessageType = 5
	ProxyMessageType_PMT_MS_GS_CHOOSE_OPERATE    ProxyMessageType = 6
	ProxyMessageType_PMT_GS_MS_OFFLINE           ProxyMessageType = 7
	ProxyMessageType_PMT_GS_GS_FRIEND_OPERATE    ProxyMessageType = 8
	ProxyMessageType_PMT_GS_BS_QUERY_BATTLEINFO  ProxyMessageType = 9
	ProxyMessageType_PMT_BS_GS_QUERY_BATTLEINFO  ProxyMessageType = 10
	ProxyMessageType_PMT_BS_GS_FINISH_BATTLE     ProxyMessageType = 11
	ProxyMessageType_PMT_GS_MS_RECONNECT         ProxyMessageType = 12
	ProxyMessageType_PMT_MS_GS_RECONNECT         ProxyMessageType = 13
	ProxyMessageType_PMT_BS_MS_SYNCBSINFO        ProxyMessageType = 14
	ProxyMessageType_PMT_GS_MS_MAKE_TEAM_OPERATE ProxyMessageType = 15
	ProxyMessageType_PMT_MS_GS_MAKE_TEAM_OPERATE ProxyMessageType = 16
)

var ProxyMessageType_name = map[int32]string{
	0:  "PMT_GS_MS_MATCH",
	1:  "PMT_MS_BS_ALLOCBATTLEROOM",
	2:  "PMT_MS_GS_MATCH_RESULT",
	3:  "PMT_BS_MS_ALLOCBATTLEROOM",
	4:  "PMT_MS_GS_BEGIN_BATTLE",
	5:  "PMT_GS_MS_CHOOSE_OPERATE",
	6:  "PMT_MS_GS_CHOOSE_OPERATE",
	7:  "PMT_GS_MS_OFFLINE",
	8:  "PMT_GS_GS_FRIEND_OPERATE",
	9:  "PMT_GS_BS_QUERY_BATTLEINFO",
	10: "PMT_BS_GS_QUERY_BATTLEINFO",
	11: "PMT_BS_GS_FINISH_BATTLE",
	12: "PMT_GS_MS_RECONNECT",
	13: "PMT_MS_GS_RECONNECT",
	14: "PMT_BS_MS_SYNCBSINFO",
	15: "PMT_GS_MS_MAKE_TEAM_OPERATE",
	16: "PMT_MS_GS_MAKE_TEAM_OPERATE",
}
var ProxyMessageType_value = map[string]int32{
	"PMT_GS_MS_MATCH":             0,
	"PMT_MS_BS_ALLOCBATTLEROOM":   1,
	"PMT_MS_GS_MATCH_RESULT":      2,
	"PMT_BS_MS_ALLOCBATTLEROOM":   3,
	"PMT_MS_GS_BEGIN_BATTLE":      4,
	"PMT_GS_MS_CHOOSE_OPERATE":    5,
	"PMT_MS_GS_CHOOSE_OPERATE":    6,
	"PMT_GS_MS_OFFLINE":           7,
	"PMT_GS_GS_FRIEND_OPERATE":    8,
	"PMT_GS_BS_QUERY_BATTLEINFO":  9,
	"PMT_BS_GS_QUERY_BATTLEINFO":  10,
	"PMT_BS_GS_FINISH_BATTLE":     11,
	"PMT_GS_MS_RECONNECT":         12,
	"PMT_MS_GS_RECONNECT":         13,
	"PMT_BS_MS_SYNCBSINFO":        14,
	"PMT_GS_MS_MAKE_TEAM_OPERATE": 15,
	"PMT_MS_GS_MAKE_TEAM_OPERATE": 16,
}

func (x ProxyMessageType) String() string {
	return proto.EnumName(ProxyMessageType_name, int32(x))
}
func (ProxyMessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// proxy message protocol
type InternalMessage struct {
	Fromid   int32  `protobuf:"varint,1,opt,name=fromid" json:"fromid,omitempty"`
	Fromtype string `protobuf:"bytes,2,opt,name=fromtype" json:"fromtype,omitempty"`
	Toid     int32  `protobuf:"varint,3,opt,name=toid" json:"toid,omitempty"`
	Totype   string `protobuf:"bytes,4,opt,name=totype" json:"totype,omitempty"`
	Charid   uint32 `protobuf:"varint,5,opt,name=charid" json:"charid,omitempty"`
	Msgid    uint32 `protobuf:"varint,6,opt,name=msgid" json:"msgid,omitempty"`
	Msgdata  []byte `protobuf:"bytes,7,opt,name=msgdata,proto3" json:"msgdata,omitempty"`
	Time     int64  `protobuf:"varint,8,opt,name=time" json:"time,omitempty"`
}

func (m *InternalMessage) Reset()                    { *m = InternalMessage{} }
func (m *InternalMessage) String() string            { return proto.CompactTextString(m) }
func (*InternalMessage) ProtoMessage()               {}
func (*InternalMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Proxy_GS_MS_Match struct {
	Charid    uint32 `protobuf:"varint,1,opt,name=charid" json:"charid,omitempty"`
	Charname  string `protobuf:"bytes,2,opt,name=charname" json:"charname,omitempty"`
	Matchmode int32  `protobuf:"varint,3,opt,name=matchmode" json:"matchmode,omitempty"`
	Mapid     int32  `protobuf:"varint,4,opt,name=mapid" json:"mapid,omitempty"`
	Action    int32  `protobuf:"varint,5,opt,name=action" json:"action,omitempty"`
}

func (m *Proxy_GS_MS_Match) Reset()                    { *m = Proxy_GS_MS_Match{} }
func (m *Proxy_GS_MS_Match) String() string            { return proto.CompactTextString(m) }
func (*Proxy_GS_MS_Match) ProtoMessage()               {}
func (*Proxy_GS_MS_Match) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Proxy_GS_MS_MakeTeamOperate struct {
	Action        int32  `protobuf:"varint,1,opt,name=action" json:"action,omitempty"`
	Matchmode     int32  `protobuf:"varint,2,opt,name=matchmode" json:"matchmode,omitempty"`
	Mapid         int32  `protobuf:"varint,3,opt,name=mapid" json:"mapid,omitempty"`
	Targetid      uint32 `protobuf:"varint,4,opt,name=targetid" json:"targetid,omitempty"`
	Benchid       int32  `protobuf:"varint,5,opt,name=benchid" json:"benchid,omitempty"`
	Matchserverid int32  `protobuf:"varint,6,opt,name=matchserverid" json:"matchserverid,omitempty"`
	Targetgsid    int32  `protobuf:"varint,7,opt,name=targetgsid" json:"targetgsid,omitempty"`
	ActorCharname string `protobuf:"bytes,8,opt,name=actor_charname" json:"actor_charname,omitempty"`
}

func (m *Proxy_GS_MS_MakeTeamOperate) Reset()                    { *m = Proxy_GS_MS_MakeTeamOperate{} }
func (m *Proxy_GS_MS_MakeTeamOperate) String() string            { return proto.CompactTextString(m) }
func (*Proxy_GS_MS_MakeTeamOperate) ProtoMessage()               {}
func (*Proxy_GS_MS_MakeTeamOperate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Proxy_GS_MS_Offline struct {
	Charid uint32 `protobuf:"varint,1,opt,name=charid" json:"charid,omitempty"`
}

func (m *Proxy_GS_MS_Offline) Reset()                    { *m = Proxy_GS_MS_Offline{} }
func (m *Proxy_GS_MS_Offline) String() string            { return proto.CompactTextString(m) }
func (*Proxy_GS_MS_Offline) ProtoMessage()               {}
func (*Proxy_GS_MS_Offline) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Proxy_GS_BS_Query_BattleInfo struct {
	Charid uint32 `protobuf:"varint,1,opt,name=charid" json:"charid,omitempty"`
}

func (m *Proxy_GS_BS_Query_BattleInfo) Reset()                    { *m = Proxy_GS_BS_Query_BattleInfo{} }
func (m *Proxy_GS_BS_Query_BattleInfo) String() string            { return proto.CompactTextString(m) }
func (*Proxy_GS_BS_Query_BattleInfo) ProtoMessage()               {}
func (*Proxy_GS_BS_Query_BattleInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Proxy_GS_MS_Reconnect struct {
	Charid uint32 `protobuf:"varint,1,opt,name=charid" json:"charid,omitempty"`
}

func (m *Proxy_GS_MS_Reconnect) Reset()                    { *m = Proxy_GS_MS_Reconnect{} }
func (m *Proxy_GS_MS_Reconnect) String() string            { return proto.CompactTextString(m) }
func (*Proxy_GS_MS_Reconnect) ProtoMessage()               {}
func (*Proxy_GS_MS_Reconnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Proxy_MS_BS_AllocBattleRoom struct {
	Matchmode    int32                                     `protobuf:"varint,1,opt,name=matchmode" json:"matchmode,omitempty"`
	Mapid        int32                                     `protobuf:"varint,2,opt,name=mapid" json:"mapid,omitempty"`
	Matchtableid int32                                     `protobuf:"varint,3,opt,name=matchtableid" json:"matchtableid,omitempty"`
	Members      []*Proxy_MS_BS_AllocBattleRoom_MemberInfo `protobuf:"bytes,4,rep,name=members" json:"members,omitempty"`
}

func (m *Proxy_MS_BS_AllocBattleRoom) Reset()                    { *m = Proxy_MS_BS_AllocBattleRoom{} }
func (m *Proxy_MS_BS_AllocBattleRoom) String() string            { return proto.CompactTextString(m) }
func (*Proxy_MS_BS_AllocBattleRoom) ProtoMessage()               {}
func (*Proxy_MS_BS_AllocBattleRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Proxy_MS_BS_AllocBattleRoom) GetMembers() []*Proxy_MS_BS_AllocBattleRoom_MemberInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

type Proxy_MS_BS_AllocBattleRoom_MemberInfo struct {
	CharID       uint32 `protobuf:"varint,1,opt,name=CharID" json:"CharID,omitempty"`
	CharName     string `protobuf:"bytes,2,opt,name=CharName" json:"CharName,omitempty"`
	CharType     int32  `protobuf:"varint,3,opt,name=CharType" json:"CharType,omitempty"`
	TeamID       int32  `protobuf:"varint,4,opt,name=TeamID" json:"TeamID,omitempty"`
	OwnerID      uint32 `protobuf:"varint,5,opt,name=OwnerID" json:"OwnerID,omitempty"`
	GameServerID int32  `protobuf:"varint,6,opt,name=GameServerID" json:"GameServerID,omitempty"`
}

func (m *Proxy_MS_BS_AllocBattleRoom_MemberInfo) Reset() {
	*m = Proxy_MS_BS_AllocBattleRoom_MemberInfo{}
}
func (m *Proxy_MS_BS_AllocBattleRoom_MemberInfo) String() string { return proto.CompactTextString(m) }
func (*Proxy_MS_BS_AllocBattleRoom_MemberInfo) ProtoMessage()    {}
func (*Proxy_MS_BS_AllocBattleRoom_MemberInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

type Proxy_MS_GS_Begin_Battle struct {
	BattleRoomID int32  `protobuf:"varint,1,opt,name=BattleRoomID" json:"BattleRoomID,omitempty"`
	BattleAddr   string `protobuf:"bytes,2,opt,name=BattleAddr" json:"BattleAddr,omitempty"`
	BattleKey    []byte `protobuf:"bytes,3,opt,name=BattleKey,proto3" json:"BattleKey,omitempty"`
}

func (m *Proxy_MS_GS_Begin_Battle) Reset()                    { *m = Proxy_MS_GS_Begin_Battle{} }
func (m *Proxy_MS_GS_Begin_Battle) String() string            { return proto.CompactTextString(m) }
func (*Proxy_MS_GS_Begin_Battle) ProtoMessage()               {}
func (*Proxy_MS_GS_Begin_Battle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Proxy_MS_GS_Reconnect struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *Proxy_MS_GS_Reconnect) Reset()                    { *m = Proxy_MS_GS_Reconnect{} }
func (m *Proxy_MS_GS_Reconnect) String() string            { return proto.CompactTextString(m) }
func (*Proxy_MS_GS_Reconnect) ProtoMessage()               {}
func (*Proxy_MS_GS_Reconnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type Proxy_BS_MS_AllocBattleRoom struct {
	Retcode        int32  `protobuf:"varint,1,opt,name=retcode" json:"retcode,omitempty"`
	Matchtableid   int32  `protobuf:"varint,2,opt,name=matchtableid" json:"matchtableid,omitempty"`
	Battleroomid   int32  `protobuf:"varint,3,opt,name=battleroomid" json:"battleroomid,omitempty"`
	Battleroomkey  []byte `protobuf:"bytes,4,opt,name=battleroomkey,proto3" json:"battleroomkey,omitempty"`
	Battleserverid int32  `protobuf:"varint,5,opt,name=battleserverid" json:"battleserverid,omitempty"`
	Connectaddr    string `protobuf:"bytes,6,opt,name=connectaddr" json:"connectaddr,omitempty"`
}

func (m *Proxy_BS_MS_AllocBattleRoom) Reset()                    { *m = Proxy_BS_MS_AllocBattleRoom{} }
func (m *Proxy_BS_MS_AllocBattleRoom) String() string            { return proto.CompactTextString(m) }
func (*Proxy_BS_MS_AllocBattleRoom) ProtoMessage()               {}
func (*Proxy_BS_MS_AllocBattleRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type Proxy_BS_GS_Query_BattleInfo struct {
	CharID     uint32 `protobuf:"varint,1,opt,name=CharID" json:"CharID,omitempty"`
	InBattle   bool   `protobuf:"varint,2,opt,name=InBattle" json:"InBattle,omitempty"`
	BattleKey  []byte `protobuf:"bytes,3,opt,name=BattleKey,proto3" json:"BattleKey,omitempty"`
	BattleAddr string `protobuf:"bytes,4,opt,name=BattleAddr" json:"BattleAddr,omitempty"`
}

func (m *Proxy_BS_GS_Query_BattleInfo) Reset()                    { *m = Proxy_BS_GS_Query_BattleInfo{} }
func (m *Proxy_BS_GS_Query_BattleInfo) String() string            { return proto.CompactTextString(m) }
func (*Proxy_BS_GS_Query_BattleInfo) ProtoMessage()               {}
func (*Proxy_BS_GS_Query_BattleInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type Proxy_BS_GS_FINISH_BATTLE struct {
	CharID uint32 `protobuf:"varint,1,opt,name=CharID" json:"CharID,omitempty"`
}

func (m *Proxy_BS_GS_FINISH_BATTLE) Reset()                    { *m = Proxy_BS_GS_FINISH_BATTLE{} }
func (m *Proxy_BS_GS_FINISH_BATTLE) String() string            { return proto.CompactTextString(m) }
func (*Proxy_BS_GS_FINISH_BATTLE) ProtoMessage()               {}
func (*Proxy_BS_GS_FINISH_BATTLE) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type Proxy_BS_MS_SyncBSInfo struct {
	BattleServerID    int32 `protobuf:"varint,1,opt,name=BattleServerID" json:"BattleServerID,omitempty"`
	BattleRoomCount   int32 `protobuf:"varint,2,opt,name=BattleRoomCount" json:"BattleRoomCount,omitempty"`
	BattleMemberCount int32 `protobuf:"varint,3,opt,name=BattleMemberCount" json:"BattleMemberCount,omitempty"`
	UDPCount          int32 `protobuf:"varint,4,opt,name=UDPCount" json:"UDPCount,omitempty"`
}

func (m *Proxy_BS_MS_SyncBSInfo) Reset()                    { *m = Proxy_BS_MS_SyncBSInfo{} }
func (m *Proxy_BS_MS_SyncBSInfo) String() string            { return proto.CompactTextString(m) }
func (*Proxy_BS_MS_SyncBSInfo) ProtoMessage()               {}
func (*Proxy_BS_MS_SyncBSInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func init() {
	proto.RegisterType((*InternalMessage)(nil), "proxymsg.InternalMessage")
	proto.RegisterType((*Proxy_GS_MS_Match)(nil), "proxymsg.Proxy_GS_MS_Match")
	proto.RegisterType((*Proxy_GS_MS_MakeTeamOperate)(nil), "proxymsg.Proxy_GS_MS_MakeTeamOperate")
	proto.RegisterType((*Proxy_GS_MS_Offline)(nil), "proxymsg.Proxy_GS_MS_Offline")
	proto.RegisterType((*Proxy_GS_BS_Query_BattleInfo)(nil), "proxymsg.Proxy_GS_BS_Query_BattleInfo")
	proto.RegisterType((*Proxy_GS_MS_Reconnect)(nil), "proxymsg.Proxy_GS_MS_Reconnect")
	proto.RegisterType((*Proxy_MS_BS_AllocBattleRoom)(nil), "proxymsg.Proxy_MS_BS_AllocBattleRoom")
	proto.RegisterType((*Proxy_MS_BS_AllocBattleRoom_MemberInfo)(nil), "proxymsg.Proxy_MS_BS_AllocBattleRoom.MemberInfo")
	proto.RegisterType((*Proxy_MS_GS_Begin_Battle)(nil), "proxymsg.Proxy_MS_GS_Begin_Battle")
	proto.RegisterType((*Proxy_MS_GS_Reconnect)(nil), "proxymsg.Proxy_MS_GS_Reconnect")
	proto.RegisterType((*Proxy_BS_MS_AllocBattleRoom)(nil), "proxymsg.Proxy_BS_MS_AllocBattleRoom")
	proto.RegisterType((*Proxy_BS_GS_Query_BattleInfo)(nil), "proxymsg.Proxy_BS_GS_Query_BattleInfo")
	proto.RegisterType((*Proxy_BS_GS_FINISH_BATTLE)(nil), "proxymsg.Proxy_BS_GS_FINISH_BATTLE")
	proto.RegisterType((*Proxy_BS_MS_SyncBSInfo)(nil), "proxymsg.Proxy_BS_MS_SyncBSInfo")
	proto.RegisterEnum("proxymsg.ProxyMessageType", ProxyMessageType_name, ProxyMessageType_value)
}

var fileDescriptor0 = []byte{
	// 1013 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x56, 0x5b, 0x6f, 0xe3, 0x44,
	0x14, 0xc6, 0xb9, 0x35, 0x9d, 0x36, 0xad, 0x77, 0x76, 0xb7, 0x1b, 0xba, 0x0b, 0xac, 0x2c, 0x2e,
	0x15, 0x82, 0x82, 0x58, 0x89, 0xf7, 0x24, 0x75, 0x5b, 0xb3, 0x49, 0x5c, 0xc6, 0xee, 0xc3, 0x3e,
	0x59, 0x8e, 0x33, 0x4d, 0xa3, 0xc6, 0x76, 0xe5, 0x78, 0x81, 0x48, 0xfc, 0x04, 0x1e, 0x90, 0xf8,
	0x27, 0x88, 0xbf, 0xc1, 0x6f, 0xe1, 0x0d, 0x89, 0x37, 0xce, 0x5c, 0x7d, 0xd9, 0x4d, 0xa5, 0xaa,
	0x9a, 0xf3, 0x9d, 0x73, 0xe6, 0xdc, 0xbe, 0xe3, 0x09, 0xda, 0xbb, 0xcf, 0xd2, 0x5f, 0x36, 0xa7,
	0xf0, 0x3f, 0x4f, 0x71, 0x97, 0x0b, 0xf1, 0x7a, 0x61, 0xfd, 0x6d, 0xa0, 0x43, 0x27, 0xc9, 0x69,
	0x96, 0x84, 0xab, 0x09, 0x5d, 0xaf, 0xc3, 0x05, 0xc5, 0x47, 0xa8, 0x73, 0x93, 0xa5, 0xf1, 0x72,
	0xde, 0x37, 0x5e, 0x1a, 0x27, 0x6d, 0x22, 0x25, 0x7c, 0x8c, 0xba, 0xec, 0x94, 0x6f, 0xee, 0x69,
	0xbf, 0x01, 0x9a, 0x5d, 0xa2, 0x65, 0x8c, 0x51, 0x2b, 0x4f, 0xc1, 0xa3, 0xc9, 0x3d, 0xf8, 0x99,
	0xdd, 0x93, 0xa7, 0xdc, 0xba, 0xc5, 0xad, 0xa5, 0xc4, 0xf0, 0xe8, 0x36, 0xcc, 0xc0, 0xba, 0x0d,
	0x78, 0x8f, 0x48, 0x09, 0x3f, 0x41, 0x6d, 0x48, 0x09, 0xe0, 0x0e, 0x87, 0x85, 0x80, 0xfb, 0x68,
	0x07, 0x0e, 0xf3, 0x30, 0x0f, 0xfb, 0x3b, 0x80, 0xef, 0x13, 0x25, 0xf2, 0x98, 0xcb, 0x98, 0xf6,
	0xbb, 0x00, 0x37, 0x09, 0x3f, 0x5b, 0x7f, 0x18, 0xe8, 0xd1, 0x15, 0x2b, 0x2e, 0xb8, 0xf0, 0x82,
	0x09, 0xfc, 0x85, 0x79, 0x74, 0x5b, 0x8a, 0x68, 0x54, 0x22, 0x42, 0x45, 0xec, 0x94, 0x84, 0xb1,
	0xae, 0x48, 0xc9, 0xf8, 0x05, 0xda, 0x8d, 0x99, 0x73, 0x9c, 0xce, 0xa9, 0x2c, 0xab, 0x00, 0x78,
	0xae, 0xe1, 0x3d, 0x5c, 0xd8, 0xe2, 0x1a, 0x21, 0xb0, 0x38, 0x61, 0x94, 0x2f, 0xd3, 0x84, 0x57,
	0x06, 0x9d, 0x13, 0x92, 0xf5, 0x5b, 0x03, 0x3d, 0xaf, 0x66, 0x75, 0x47, 0x7d, 0x1a, 0xc6, 0xee,
	0x3d, 0xcd, 0xc2, 0x9c, 0x96, 0xfc, 0x8c, 0xb2, 0x5f, 0x35, 0x87, 0xc6, 0xd6, 0x1c, 0x9a, 0xe5,
	0x1c, 0xa0, 0xa6, 0x3c, 0xcc, 0x16, 0x34, 0x97, 0xc9, 0xf5, 0x88, 0x96, 0x59, 0x2f, 0x67, 0x34,
	0x89, 0x6e, 0x65, 0xeb, 0xdb, 0x44, 0x89, 0xf8, 0x53, 0xd4, 0xe3, 0x17, 0xaf, 0x69, 0xf6, 0x13,
	0xcd, 0xe4, 0x0c, 0xda, 0xa4, 0x0a, 0xe2, 0x8f, 0x11, 0x12, 0x77, 0x2d, 0xd6, 0x60, 0xb2, 0xc3,
	0x4d, 0x4a, 0x08, 0xfe, 0x0c, 0x1d, 0x40, 0xe6, 0x69, 0x16, 0xe8, 0xae, 0x76, 0x79, 0x57, 0x7b,
	0x1c, 0x1d, 0x49, 0xd0, 0xfa, 0x1a, 0x3d, 0x2e, 0x77, 0xc3, 0xbd, 0xb9, 0x59, 0x2d, 0x13, 0xba,
	0x6d, 0x4a, 0xd6, 0xf7, 0xe8, 0x85, 0x36, 0x1f, 0x7a, 0xc1, 0x8f, 0x6f, 0x69, 0xb6, 0x09, 0x86,
	0x61, 0x9e, 0xaf, 0xa8, 0x93, 0xdc, 0xa4, 0x5b, 0xfd, 0xbe, 0x41, 0x4f, 0xcb, 0x61, 0x08, 0x8d,
	0xd2, 0x24, 0xa1, 0x51, 0xbe, 0xd5, 0xe1, 0x5f, 0x3d, 0xa6, 0x09, 0x8f, 0x34, 0x58, 0xad, 0xd2,
	0x48, 0x04, 0x22, 0x69, 0x1a, 0x57, 0xc7, 0x61, 0x6c, 0x1d, 0x47, 0xa3, 0x3c, 0x0e, 0x0b, 0xed,
	0x73, 0x93, 0x3c, 0x9c, 0xad, 0xa8, 0x9e, 0x55, 0x05, 0xc3, 0x3f, 0x00, 0xc5, 0x69, 0x3c, 0xa3,
	0xd9, 0x1a, 0x26, 0xd6, 0x3c, 0xd9, 0xfb, 0xee, 0xdb, 0x53, 0xb5, 0xa0, 0xa7, 0x0f, 0xe4, 0x73,
	0x3a, 0xe1, 0x4e, 0xac, 0x07, 0x44, 0x5d, 0x70, 0xfc, 0xa7, 0x81, 0x50, 0x81, 0xb3, 0x52, 0x59,
	0xdb, 0x9d, 0x33, 0x55, 0xaa, 0x90, 0x18, 0x4b, 0xd8, 0x69, 0x5a, 0x62, 0xbe, 0x92, 0x95, 0xce,
	0x67, 0x9b, 0x2b, 0xd2, 0xd5, 0x32, 0xbb, 0x8f, 0x11, 0x17, 0xee, 0x13, 0xc4, 0x97, 0x12, 0x63,
	0x96, 0xfb, 0x73, 0x42, 0x59, 0x20, 0xb1, 0xd4, 0x4a, 0x64, 0x0d, 0xb8, 0x80, 0x5b, 0x3d, 0xce,
	0x21, 0x50, 0x0b, 0x62, 0x55, 0x30, 0xeb, 0x57, 0xd4, 0xd7, 0x75, 0xb2, 0x21, 0xd3, 0xc5, 0x32,
	0x91, 0x13, 0x66, 0xfe, 0x45, 0xc9, 0xb2, 0x0e, 0xf0, 0x2f, 0x63, 0x8c, 0x97, 0x42, 0x1e, 0xcc,
	0xe7, 0x99, 0xac, 0xa7, 0x84, 0xb0, 0xc1, 0x09, 0xe9, 0x35, 0xdd, 0xf0, 0x92, 0xf6, 0x49, 0x01,
	0x58, 0x5f, 0x28, 0x9e, 0x88, 0xe8, 0x05, 0x4f, 0x0e, 0x50, 0x23, 0xbd, 0xe3, 0x01, 0xbb, 0x04,
	0x4e, 0xd6, 0x3f, 0x86, 0xe2, 0xc7, 0x90, 0x33, 0xaa, 0xce, 0x0f, 0x68, 0x42, 0x46, 0xf3, 0xa8,
	0x60, 0x87, 0x12, 0xdf, 0x61, 0x41, 0xe3, 0x3d, 0x2c, 0x00, 0x9b, 0x19, 0xbf, 0x2b, 0x4b, 0xf9,
	0xc7, 0x57, 0x32, 0xa5, 0x8c, 0xb1, 0x35, 0x2d, 0xe4, 0x3b, 0x28, 0xa6, 0xc5, 0x8b, 0xa9, 0x82,
	0xf8, 0x73, 0x74, 0x20, 0x00, 0xbd, 0xcd, 0x62, 0xdb, 0x6b, 0x28, 0x7e, 0x89, 0xf6, 0x64, 0xa9,
	0x21, 0xeb, 0x5b, 0x87, 0xf7, 0xad, 0x0c, 0x59, 0xbf, 0x1b, 0x6a, 0xf7, 0x86, 0xbc, 0x37, 0xef,
	0xdb, 0xbd, 0x6d, 0xfc, 0x72, 0x12, 0x61, 0xc7, 0x8b, 0xed, 0x12, 0x2d, 0x3f, 0x3c, 0x8d, 0xda,
	0x2c, 0x5b, 0xf5, 0x59, 0x5a, 0xaf, 0xd0, 0x87, 0xe5, 0x8c, 0xce, 0x9d, 0xa9, 0xe3, 0x5d, 0x06,
	0xc3, 0x81, 0xef, 0x8f, 0xed, 0x6d, 0xe9, 0x58, 0x7f, 0x19, 0xe8, 0xa8, 0x3c, 0x39, 0x6f, 0x93,
	0x44, 0x43, 0x8f, 0x57, 0x00, 0xcd, 0x12, 0xb7, 0x6b, 0x86, 0x8a, 0xd9, 0xd5, 0x50, 0x7c, 0x82,
	0x0e, 0x8b, 0x51, 0x8f, 0xd2, 0xb7, 0x49, 0x2e, 0xa7, 0x58, 0x87, 0xf1, 0x57, 0xe8, 0x91, 0x80,
	0xc4, 0x1e, 0x0a, 0x5b, 0x31, 0xcd, 0x77, 0x15, 0xac, 0x53, 0xd7, 0x67, 0x57, 0xc2, 0x48, 0xec,
	0x94, 0x96, 0xbf, 0xfc, 0xaf, 0x89, 0x4c, 0x9e, 0xb6, 0x7c, 0x9a, 0xf9, 0x0a, 0x3e, 0x46, 0x87,
	0x57, 0x13, 0x5f, 0xbd, 0x24, 0x03, 0x7f, 0x74, 0x69, 0x7e, 0x80, 0x3f, 0x82, 0xae, 0x00, 0x28,
	0xbf, 0x13, 0xe3, 0xb1, 0x3b, 0x12, 0x1d, 0x21, 0xae, 0x3b, 0x31, 0x0d, 0x08, 0x72, 0x24, 0xd5,
	0x17, 0xd2, 0x27, 0x20, 0xb6, 0x77, 0x3d, 0xf6, 0xcd, 0x86, 0x72, 0x95, 0x94, 0xae, 0xb9, 0x36,
	0xab, 0xae, 0x43, 0xfb, 0xc2, 0x99, 0xca, 0x66, 0x9b, 0x2d, 0x98, 0x64, 0xbf, 0x48, 0x65, 0x74,
	0xe9, 0xba, 0x9e, 0x1d, 0xb8, 0x57, 0x36, 0x19, 0xf8, 0xb6, 0xd9, 0x56, 0x5a, 0xe1, 0x59, 0xd3,
	0x76, 0xf0, 0x53, 0x78, 0xa8, 0xb5, 0xaf, 0x7b, 0x7e, 0x3e, 0x76, 0xa6, 0xb6, 0xb9, 0x53, 0xba,
	0x92, 0x0d, 0x97, 0x38, 0xf6, 0xf4, 0x4c, 0x3b, 0x75, 0x81, 0x1c, 0xc7, 0x52, 0xcb, 0x1e, 0x82,
	0x6b, 0x9b, 0xbc, 0x91, 0xc9, 0x38, 0xd3, 0x73, 0xd7, 0xdc, 0x55, 0x7a, 0x49, 0xd6, 0xba, 0x1e,
	0xe1, 0xe7, 0xe8, 0x59, 0xa1, 0xaf, 0x50, 0xc7, 0xdc, 0xc3, 0xcf, 0xe0, 0x59, 0xd2, 0x19, 0x11,
	0x7b, 0xe4, 0x4e, 0xa7, 0xf6, 0xc8, 0x37, 0xf7, 0x95, 0x42, 0x7e, 0x1e, 0xb4, 0xa2, 0x07, 0x0b,
	0xff, 0xa4, 0x68, 0x9d, 0xf7, 0x66, 0x3a, 0x02, 0x4e, 0xb1, 0x40, 0x07, 0xf8, 0x13, 0xf8, 0x52,
	0x94, 0x86, 0xf4, 0xda, 0x0e, 0x7c, 0x7b, 0x30, 0xd1, 0x95, 0x1c, 0x2a, 0x03, 0x35, 0x91, 0xba,
	0x81, 0x39, 0xeb, 0xf0, 0x9f, 0x6a, 0xaf, 0xfe, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x37, 0x95, 0x75,
	0x41, 0xb9, 0x09, 0x00, 0x00,
}
