// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

/*
Package proxymsg is a generated protocol buffer package.

It is generated from these files:
	proxy.proto

It has these top-level messages:
	InternalMessage
	Proxy_GS_BS_SyncPlayerInfo
	Proxy_GS_MS_Match
	Proxy_MS_BS_AllocBattleRoom
	Proxy_MS_GS_MatchResult
	Proxy_BS_MS_AllocBattleRoom
	Proxy_BS_GS_SyncPlayerInfo
*/
package proxymsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProxyMessageType int32

const (
	ProxyMessageType_PMT_GS_BS_SYNCPLAYERINFO  ProxyMessageType = 0
	ProxyMessageType_PMT_GS_MS_MATCH           ProxyMessageType = 1
	ProxyMessageType_PMT_MS_BS_ALLOCBATTLEROOM ProxyMessageType = 2
	ProxyMessageType_PMT_MS_GS_MATCHRESULT     ProxyMessageType = 3
	ProxyMessageType_PMT_BS_MS_ALLOCBATTLEROOM ProxyMessageType = 4
	ProxyMessageType_PMT_BS_GS_SYNCPLAYERINFO  ProxyMessageType = 5
)

var ProxyMessageType_name = map[int32]string{
	0: "PMT_GS_BS_SYNCPLAYERINFO",
	1: "PMT_GS_MS_MATCH",
	2: "PMT_MS_BS_ALLOCBATTLEROOM",
	3: "PMT_MS_GS_MATCHRESULT",
	4: "PMT_BS_MS_ALLOCBATTLEROOM",
	5: "PMT_BS_GS_SYNCPLAYERINFO",
}
var ProxyMessageType_value = map[string]int32{
	"PMT_GS_BS_SYNCPLAYERINFO":  0,
	"PMT_GS_MS_MATCH":           1,
	"PMT_MS_BS_ALLOCBATTLEROOM": 2,
	"PMT_MS_GS_MATCHRESULT":     3,
	"PMT_BS_MS_ALLOCBATTLEROOM": 4,
	"PMT_BS_GS_SYNCPLAYERINFO":  5,
}

func (x ProxyMessageType) Enum() *ProxyMessageType {
	p := new(ProxyMessageType)
	*p = x
	return p
}
func (x ProxyMessageType) String() string {
	return proto.EnumName(ProxyMessageType_name, int32(x))
}
func (x *ProxyMessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProxyMessageType_value, data, "ProxyMessageType")
	if err != nil {
		return err
	}
	*x = ProxyMessageType(value)
	return nil
}
func (ProxyMessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// proxy message protocol
type InternalMessage struct {
	Fromid           *int32  `protobuf:"varint,1,req,name=fromid" json:"fromid,omitempty"`
	Fromtype         *string `protobuf:"bytes,2,req,name=fromtype" json:"fromtype,omitempty"`
	Toid             *int32  `protobuf:"varint,3,req,name=toid" json:"toid,omitempty"`
	Totype           *string `protobuf:"bytes,4,req,name=totype" json:"totype,omitempty"`
	Charid           *string `protobuf:"bytes,5,opt,name=charid" json:"charid,omitempty"`
	Msgid            *uint32 `protobuf:"varint,6,opt,name=msgid" json:"msgid,omitempty"`
	Msgdata          []byte  `protobuf:"bytes,7,opt,name=msgdata" json:"msgdata,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InternalMessage) Reset()                    { *m = InternalMessage{} }
func (m *InternalMessage) String() string            { return proto.CompactTextString(m) }
func (*InternalMessage) ProtoMessage()               {}
func (*InternalMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InternalMessage) GetFromid() int32 {
	if m != nil && m.Fromid != nil {
		return *m.Fromid
	}
	return 0
}

func (m *InternalMessage) GetFromtype() string {
	if m != nil && m.Fromtype != nil {
		return *m.Fromtype
	}
	return ""
}

func (m *InternalMessage) GetToid() int32 {
	if m != nil && m.Toid != nil {
		return *m.Toid
	}
	return 0
}

func (m *InternalMessage) GetTotype() string {
	if m != nil && m.Totype != nil {
		return *m.Totype
	}
	return ""
}

func (m *InternalMessage) GetCharid() string {
	if m != nil && m.Charid != nil {
		return *m.Charid
	}
	return ""
}

func (m *InternalMessage) GetMsgid() uint32 {
	if m != nil && m.Msgid != nil {
		return *m.Msgid
	}
	return 0
}

func (m *InternalMessage) GetMsgdata() []byte {
	if m != nil {
		return m.Msgdata
	}
	return nil
}

type Proxy_GS_BS_SyncPlayerInfo struct {
	Charid           *string `protobuf:"bytes,1,req,name=charid" json:"charid,omitempty"`
	Chartype         *int32  `protobuf:"varint,2,req,name=chartype" json:"chartype,omitempty"`
	Charname         *string `protobuf:"bytes,3,req,name=charname" json:"charname,omitempty"`
	Teamtype         *int32  `protobuf:"varint,4,req,name=teamtype" json:"teamtype,omitempty"`
	Battleroomid     *int32  `protobuf:"varint,5,req,name=battleroomid" json:"battleroomid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Proxy_GS_BS_SyncPlayerInfo) Reset()                    { *m = Proxy_GS_BS_SyncPlayerInfo{} }
func (m *Proxy_GS_BS_SyncPlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*Proxy_GS_BS_SyncPlayerInfo) ProtoMessage()               {}
func (*Proxy_GS_BS_SyncPlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Proxy_GS_BS_SyncPlayerInfo) GetCharid() string {
	if m != nil && m.Charid != nil {
		return *m.Charid
	}
	return ""
}

func (m *Proxy_GS_BS_SyncPlayerInfo) GetChartype() int32 {
	if m != nil && m.Chartype != nil {
		return *m.Chartype
	}
	return 0
}

func (m *Proxy_GS_BS_SyncPlayerInfo) GetCharname() string {
	if m != nil && m.Charname != nil {
		return *m.Charname
	}
	return ""
}

func (m *Proxy_GS_BS_SyncPlayerInfo) GetTeamtype() int32 {
	if m != nil && m.Teamtype != nil {
		return *m.Teamtype
	}
	return 0
}

func (m *Proxy_GS_BS_SyncPlayerInfo) GetBattleroomid() int32 {
	if m != nil && m.Battleroomid != nil {
		return *m.Battleroomid
	}
	return 0
}

type Proxy_GS_MS_Match struct {
	Charid           *string `protobuf:"bytes,1,req,name=charid" json:"charid,omitempty"`
	Matchmode        *int32  `protobuf:"varint,2,req,name=matchmode" json:"matchmode,omitempty"`
	Action           *int32  `protobuf:"varint,3,req,name=action" json:"action,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Proxy_GS_MS_Match) Reset()                    { *m = Proxy_GS_MS_Match{} }
func (m *Proxy_GS_MS_Match) String() string            { return proto.CompactTextString(m) }
func (*Proxy_GS_MS_Match) ProtoMessage()               {}
func (*Proxy_GS_MS_Match) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Proxy_GS_MS_Match) GetCharid() string {
	if m != nil && m.Charid != nil {
		return *m.Charid
	}
	return ""
}

func (m *Proxy_GS_MS_Match) GetMatchmode() int32 {
	if m != nil && m.Matchmode != nil {
		return *m.Matchmode
	}
	return 0
}

func (m *Proxy_GS_MS_Match) GetAction() int32 {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return 0
}

type Proxy_MS_BS_AllocBattleRoom struct {
	Matchmode        *int32 `protobuf:"varint,1,req,name=matchmode" json:"matchmode,omitempty"`
	Matchroomid      *int32 `protobuf:"varint,2,req,name=matchroomid" json:"matchroomid,omitempty"`
	Membercnt        *int32 `protobuf:"varint,3,req,name=membercnt" json:"membercnt,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Proxy_MS_BS_AllocBattleRoom) Reset()                    { *m = Proxy_MS_BS_AllocBattleRoom{} }
func (m *Proxy_MS_BS_AllocBattleRoom) String() string            { return proto.CompactTextString(m) }
func (*Proxy_MS_BS_AllocBattleRoom) ProtoMessage()               {}
func (*Proxy_MS_BS_AllocBattleRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Proxy_MS_BS_AllocBattleRoom) GetMatchmode() int32 {
	if m != nil && m.Matchmode != nil {
		return *m.Matchmode
	}
	return 0
}

func (m *Proxy_MS_BS_AllocBattleRoom) GetMatchroomid() int32 {
	if m != nil && m.Matchroomid != nil {
		return *m.Matchroomid
	}
	return 0
}

func (m *Proxy_MS_BS_AllocBattleRoom) GetMembercnt() int32 {
	if m != nil && m.Membercnt != nil {
		return *m.Membercnt
	}
	return 0
}

type Proxy_MS_GS_MatchResult struct {
	Retcode          *int32  `protobuf:"varint,1,req,name=retcode" json:"retcode,omitempty"`
	Battleroomid     *int32  `protobuf:"varint,2,opt,name=battleroomid" json:"battleroomid,omitempty"`
	Battleserverid   *int32  `protobuf:"varint,3,opt,name=battleserverid" json:"battleserverid,omitempty"`
	Battleservername *string `protobuf:"bytes,4,opt,name=battleservername" json:"battleservername,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Proxy_MS_GS_MatchResult) Reset()                    { *m = Proxy_MS_GS_MatchResult{} }
func (m *Proxy_MS_GS_MatchResult) String() string            { return proto.CompactTextString(m) }
func (*Proxy_MS_GS_MatchResult) ProtoMessage()               {}
func (*Proxy_MS_GS_MatchResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Proxy_MS_GS_MatchResult) GetRetcode() int32 {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return 0
}

func (m *Proxy_MS_GS_MatchResult) GetBattleroomid() int32 {
	if m != nil && m.Battleroomid != nil {
		return *m.Battleroomid
	}
	return 0
}

func (m *Proxy_MS_GS_MatchResult) GetBattleserverid() int32 {
	if m != nil && m.Battleserverid != nil {
		return *m.Battleserverid
	}
	return 0
}

func (m *Proxy_MS_GS_MatchResult) GetBattleservername() string {
	if m != nil && m.Battleservername != nil {
		return *m.Battleservername
	}
	return ""
}

type Proxy_BS_MS_AllocBattleRoom struct {
	Retcode          *int32  `protobuf:"varint,1,req,name=retcode" json:"retcode,omitempty"`
	Matchroomid      *int32  `protobuf:"varint,2,opt,name=matchroomid" json:"matchroomid,omitempty"`
	Battleroomid     *int32  `protobuf:"varint,3,opt,name=battleroomid" json:"battleroomid,omitempty"`
	Battleserverid   *int32  `protobuf:"varint,4,opt,name=battleserverid" json:"battleserverid,omitempty"`
	Battleservername *string `protobuf:"bytes,5,opt,name=battleservername" json:"battleservername,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Proxy_BS_MS_AllocBattleRoom) Reset()                    { *m = Proxy_BS_MS_AllocBattleRoom{} }
func (m *Proxy_BS_MS_AllocBattleRoom) String() string            { return proto.CompactTextString(m) }
func (*Proxy_BS_MS_AllocBattleRoom) ProtoMessage()               {}
func (*Proxy_BS_MS_AllocBattleRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Proxy_BS_MS_AllocBattleRoom) GetRetcode() int32 {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return 0
}

func (m *Proxy_BS_MS_AllocBattleRoom) GetMatchroomid() int32 {
	if m != nil && m.Matchroomid != nil {
		return *m.Matchroomid
	}
	return 0
}

func (m *Proxy_BS_MS_AllocBattleRoom) GetBattleroomid() int32 {
	if m != nil && m.Battleroomid != nil {
		return *m.Battleroomid
	}
	return 0
}

func (m *Proxy_BS_MS_AllocBattleRoom) GetBattleserverid() int32 {
	if m != nil && m.Battleserverid != nil {
		return *m.Battleserverid
	}
	return 0
}

func (m *Proxy_BS_MS_AllocBattleRoom) GetBattleservername() string {
	if m != nil && m.Battleservername != nil {
		return *m.Battleservername
	}
	return ""
}

type Proxy_BS_GS_SyncPlayerInfo struct {
	Retcode          *int32  `protobuf:"varint,1,req,name=retcode" json:"retcode,omitempty"`
	Battleroomid     *int32  `protobuf:"varint,2,opt,name=battleroomid" json:"battleroomid,omitempty"`
	Battleroomkey    []byte  `protobuf:"bytes,3,opt,name=battleroomkey" json:"battleroomkey,omitempty"`
	Connectaddr      *string `protobuf:"bytes,4,opt,name=connectaddr" json:"connectaddr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Proxy_BS_GS_SyncPlayerInfo) Reset()                    { *m = Proxy_BS_GS_SyncPlayerInfo{} }
func (m *Proxy_BS_GS_SyncPlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*Proxy_BS_GS_SyncPlayerInfo) ProtoMessage()               {}
func (*Proxy_BS_GS_SyncPlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Proxy_BS_GS_SyncPlayerInfo) GetRetcode() int32 {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return 0
}

func (m *Proxy_BS_GS_SyncPlayerInfo) GetBattleroomid() int32 {
	if m != nil && m.Battleroomid != nil {
		return *m.Battleroomid
	}
	return 0
}

func (m *Proxy_BS_GS_SyncPlayerInfo) GetBattleroomkey() []byte {
	if m != nil {
		return m.Battleroomkey
	}
	return nil
}

func (m *Proxy_BS_GS_SyncPlayerInfo) GetConnectaddr() string {
	if m != nil && m.Connectaddr != nil {
		return *m.Connectaddr
	}
	return ""
}

func init() {
	proto.RegisterType((*InternalMessage)(nil), "proxymsg.InternalMessage")
	proto.RegisterType((*Proxy_GS_BS_SyncPlayerInfo)(nil), "proxymsg.Proxy_GS_BS_SyncPlayerInfo")
	proto.RegisterType((*Proxy_GS_MS_Match)(nil), "proxymsg.Proxy_GS_MS_Match")
	proto.RegisterType((*Proxy_MS_BS_AllocBattleRoom)(nil), "proxymsg.Proxy_MS_BS_AllocBattleRoom")
	proto.RegisterType((*Proxy_MS_GS_MatchResult)(nil), "proxymsg.Proxy_MS_GS_MatchResult")
	proto.RegisterType((*Proxy_BS_MS_AllocBattleRoom)(nil), "proxymsg.Proxy_BS_MS_AllocBattleRoom")
	proto.RegisterType((*Proxy_BS_GS_SyncPlayerInfo)(nil), "proxymsg.Proxy_BS_GS_SyncPlayerInfo")
	proto.RegisterEnum("proxymsg.ProxyMessageType", ProxyMessageType_name, ProxyMessageType_value)
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xdf, 0x6e, 0xda, 0x30,
	0x14, 0xc6, 0x67, 0x20, 0x14, 0x4e, 0xf9, 0x93, 0xba, 0xeb, 0x96, 0xee, 0x8f, 0x14, 0xe5, 0x2a,
	0xda, 0xc5, 0xde, 0x01, 0x10, 0x65, 0x48, 0xa4, 0x20, 0x92, 0x49, 0xeb, 0x15, 0x72, 0x13, 0x97,
	0x46, 0x8b, 0x63, 0xe4, 0x78, 0x53, 0x73, 0xb9, 0xeb, 0xbd, 0xd2, 0x1e, 0x6e, 0xb2, 0xe3, 0xd0,
	0x16, 0x56, 0x69, 0x97, 0xfe, 0x4e, 0xfc, 0x9d, 0xdf, 0xf9, 0x7c, 0x02, 0xa7, 0x3b, 0xc1, 0x1f,
	0xca, 0xcf, 0x3b, 0xc1, 0x25, 0xc7, 0x1d, 0x7d, 0x60, 0xc5, 0xd6, 0xfb, 0x85, 0x60, 0x38, 0xcf,
	0x25, 0x15, 0x39, 0xc9, 0x02, 0x5a, 0x14, 0x64, 0x4b, 0xf1, 0x00, 0xda, 0x77, 0x82, 0xb3, 0x34,
	0x71, 0x90, 0xdb, 0xf0, 0x2d, 0x6c, 0x43, 0x47, 0x9d, 0x65, 0xb9, 0xa3, 0x4e, 0xc3, 0x6d, 0xf8,
	0x5d, 0xdc, 0x83, 0x96, 0xe4, 0x69, 0xe2, 0x34, 0x75, 0x7d, 0x00, 0x6d, 0xc9, 0x75, 0xb5, 0xa5,
	0xab, 0x03, 0x68, 0xc7, 0xf7, 0x44, 0xa4, 0x89, 0x63, 0xb9, 0xc8, 0xef, 0xe2, 0x3e, 0x58, 0xac,
	0xd8, 0xa6, 0x89, 0xd3, 0x76, 0x91, 0xdf, 0xc7, 0x43, 0x38, 0x61, 0xc5, 0x36, 0x21, 0x92, 0x38,
	0x27, 0x2e, 0xf2, 0x7b, 0xde, 0x03, 0xbc, 0x5b, 0x29, 0x9e, 0xcd, 0x2c, 0xdc, 0x8c, 0xc3, 0x4d,
	0x58, 0xe6, 0xf1, 0x2a, 0x23, 0x25, 0x15, 0xf3, 0xfc, 0x8e, 0x3f, 0x71, 0x43, 0xda, 0xdd, 0x86,
	0x8e, 0x3a, 0xef, 0x69, 0xac, 0x5a, 0xc9, 0x09, 0xa3, 0x9a, 0x48, 0x7f, 0x23, 0x29, 0x61, 0x7b,
	0x26, 0x0b, 0xbf, 0x86, 0xde, 0x2d, 0x91, 0x32, 0xa3, 0x82, 0xeb, 0xc9, 0x2c, 0xa5, 0x7a, 0x57,
	0x70, 0xb6, 0xef, 0x1c, 0x84, 0x9b, 0x80, 0xc8, 0xf8, 0xfe, 0xa8, 0xe1, 0x19, 0x74, 0x99, 0x2a,
	0x30, 0x9e, 0xd4, 0x1d, 0x07, 0xd0, 0x26, 0xb1, 0x4c, 0x79, 0x5e, 0x25, 0xe0, 0x7d, 0x83, 0xf7,
	0x95, 0x4f, 0xa0, 0x27, 0x18, 0x65, 0x19, 0x8f, 0xc7, 0xba, 0xdd, 0x9a, 0x73, 0xf6, 0xdc, 0xa1,
	0xca, 0xf4, 0x1c, 0x4e, 0xb5, 0x64, 0x70, 0x2a, 0x5b, 0xf5, 0x1d, 0x65, 0xb7, 0x54, 0xc4, 0xb9,
	0x34, 0xce, 0x02, 0xde, 0xee, 0x9d, 0x67, 0x86, 0x70, 0x4d, 0x8b, 0x1f, 0x99, 0x54, 0x39, 0x0a,
	0x2a, 0xe3, 0x47, 0xcf, 0xc3, 0x19, 0x1b, 0x2e, 0xf2, 0x2d, 0xfc, 0x06, 0x06, 0x95, 0x5a, 0x50,
	0xf1, 0x93, 0x0a, 0xfd, 0x6a, 0x4a, 0x77, 0xc0, 0x7e, 0xaa, 0xeb, 0xf4, 0x5a, 0xea, 0xbd, 0xbc,
	0xdf, 0xa8, 0x1e, 0x67, 0xac, 0x63, 0x39, 0x1c, 0xe7, 0xa8, 0xf1, 0xd1, 0x30, 0xe8, 0x1f, 0x34,
	0xcd, 0x17, 0x68, 0x5a, 0x2f, 0xd2, 0xe8, 0xed, 0xf1, 0x78, 0xbd, 0x1d, 0x63, 0x9d, 0xc0, 0xc1,
	0x76, 0xfc, 0x67, 0x08, 0x17, 0xd0, 0x7f, 0x54, 0xbf, 0xd3, 0x52, 0xd3, 0xf4, 0x14, 0x78, 0xcc,
	0xf3, 0x9c, 0xc6, 0x92, 0x24, 0x89, 0xa8, 0xc6, 0xff, 0xf4, 0x07, 0x81, 0xad, 0x3b, 0x9a, 0xff,
	0x21, 0x2a, 0x77, 0x14, 0x7f, 0x00, 0x67, 0x15, 0x44, 0xf5, 0x86, 0xde, 0x5c, 0x4f, 0x56, 0x8b,
	0xd1, 0xcd, 0x74, 0x3d, 0xbf, 0xbe, 0x5a, 0xda, 0xaf, 0xf0, 0x39, 0x0c, 0x4d, 0x55, 0x6d, 0xd1,
	0x28, 0x9a, 0x7c, 0xb1, 0x11, 0xfe, 0x08, 0x97, 0x4a, 0x34, 0x2b, 0xb1, 0x58, 0x2c, 0x27, 0xe3,
	0x51, 0x14, 0x2d, 0xa6, 0xeb, 0xe5, 0x32, 0xb0, 0x1b, 0xf8, 0x12, 0x2e, 0x4c, 0x79, 0x66, 0xee,
	0xac, 0xa7, 0xe1, 0xd7, 0x45, 0x64, 0x37, 0xeb, 0x9b, 0x26, 0xfd, 0x83, 0x9b, 0xad, 0x9a, 0xc5,
	0xe4, 0xf1, 0x9c, 0xc5, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x31, 0x82, 0x2d, 0x87, 0xe9, 0x03,
	0x00, 0x00,
}
